# XDG variables settings
XDG_CONFIG_HOME='$HOME/.config'
XDG_CACHE_HOME='$HOME/.cache'
XDG_DATA_HOME='$HOME/.local/share'
XDG_STATE_HOME='$HOME/.local/state'

# Cargo
CARGO_HOME='$XDG_DATA_HOME/cargo'

# Bash
HISTFILE='$XDG_STATE_HOME/bash/history'

# NPM
NPM_CONFIG_USERCONFIG='$XDG_CONFIG_HOME/npm/config'
NPM_CONFIG_CACHE='$XDG_CACHE_HOME/npm'
NPM_CONFIG_TMP='$XDG_RUNTIME_DIR/npm'
